version: '3'
services:
  zk:
    image: zookeeper:3.4
    networks:
      - marathonucrspawner
    ports:
      - 2181:2181
  mesos-master:
    image: dtaniwaki/mesos-master:1.4.0-2.0.1
    command: mesos-master --registry=in_memory --port=5050 --zk=zk://zk:2181/mesos --log_dir=/var/log/mesos --logging_level=WARNING
    networks:
      - marathonucrspawner
    ports:
      - 5050:5050
    expose:
      - 5050
    depends_on:
      - zk
  mesos-slave:
    image: dtaniwaki/mesos-slave:1.4.0-2.0.1
    command: mesos-slave --port=5051 --master=zk://zk:2181/mesos --work_dir=/var/lib/mesos --log_dir=/var/log/mesos --hostname=mesos-slave --isolation=filesystem/linux,docker/runtime --image_providers=docker --logging_level=WARNING --docker_store_dir=/docker-store --image_provisioner_backend=copy
    privileged: true
    networks:
      - marathonucrspawner
    ports:
      - 5051:5051
    expose:
      - 5051
    volumes:
      - mesos-docker-store:/docker-store
    depends_on:
      - mesos-master
  marathon:
    image: dtaniwaki/marathon:1.5.1
    command: --master zk://zk:2181/mesos --zk zk://zk:2181/marathon --logging_level=WARN
    networks:
      - marathonucrspawner
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mesos-master
  hub:
    build:
      context: '.'
      args:
        - JUPYTERHUB_VERSION=0.8.1
    command: bash /opt/wait.sh jupyterhub --ip 0.0.0.0 --port 8000 --debug
    user: jupyterhub # The UID is the same as anonymous user in mesos-slave
    environment:
      - JUPYTERHUB_API_IP=hub
      - JUPYTERHUB_API_PORT=8081
      - NOTEBOOK_IMAGE=jupyterhub/singleuser:0.8.1
      - MARATHON_HOST=http://marathon:8080
      - MESOS_USER=anonymous
    networks:
      - marathonucrspawner
    ports:
      - 8000:8000
      - 8081:8081
    expose:
      - 8000
      - 8081
    volumes:
      - ./wait.sh:/opt/wait.sh
    depends_on:
      - marathon
networks:
  marathonucrspawner:
volumes:
  mesos-docker-store:
